# Generated by Django 4.2 on 2023-05-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assumptionsns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='constrainns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='methodns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='modelns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='namens',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nstoassumptions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nstomodel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='refns',
            options={'managed': True},
        ),
    ]
