# Generated by Django 4.2 on 2023-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_alter_assumptionsns_assumptionsdescription_and_more'),
    ]
    """
    operations = [
        migrations.AlterField(
            model_name='constrainns',
            name='constrainvariable',
            field=models.CharField(choices=[('R', 'R'), ('M-R', 'M-R')], db_column='constrainvariable', max_length=19),
        ),
    ]
    """